#ifndef SUFS_GLOBAL_KFS_CONFIG_H_
#define SUFS_GLOBAL_KFS_CONFIG_H_

#include "config.h"

#define SUFS_KFS_DEF_DELE_THREADS_PER_SOCKET 0

#define SUFS_KFS_MAX_AGENT_PER_SOCKET (SUFS_MAX_CPU / SUFS_PM_MAX_INS)
#define SUFS_KFS_MAX_AGENT (SUFS_MAX_CPU)

#define SUFS_KFS_AGENT_TASK_MAX_SIZE (SUFS_FILE_BLOCK_PAGE_CNT + 1)

#define SUFS_KFS_AGENT_RING_BUFFER_CHECK_COUNT 220000

#define SUFS_CHECKER_RING_BUFFER_CHECK_COUNT 100000

#define SUFS_CHECKER_RING_BUFFER_EXIT_COUNT  (5000ul * SUFS_CPU_MHZ * 1000)

#define SUFS_KFS_AGENT_REQUEST_CHECK_COUNT 3000

#define SUFS_KFS_APP_CHECK_COUNT 220000000

#endif
