#ifndef SUFS_GLOBAL_CHECKER_CONFIG_H_
#define SUFS_GLOBAL_CHECKER_CONFIG_H_

#include "config.h"

#define SUFS_CHECKER_FILE_RING_ADDR 0x370000000000
#define SUFS_CHECKER_FILE_RING_SIZE (2 * 1024 * 1024)

#define SUFS_CHECKER_RES_RING_ADDR ( \
    SUFS_CHECKER_FILE_RING_ADDR + SUFS_CHECKER_FILE_RING_SIZE \
)
#define SUFS_CHECKER_RES_RING_SIZE (2 * 1024 * 1024)

#define SUFS_STATE_ADDR 0x300000000000
#define SUFS_INODE_STATE_SIZE (SUFS_MAX_INODE_NUM * sizeof(int))
#define SUFS_MAPPED_STATE_SIZE (SUFS_MAX_INODE_NUM * sizeof(int))

#endif