#ifndef SUFS_GLOBAL_CONFIG_H_
#define SUFS_GLOBAL_CONFIG_H_

#define SUFS_CACHELINE 64

#define SUFS_PAGE_SIZE 4096

#define SUFS_PAGE_SHIFT 12

#define SUFS_PAGE_MASK (~(SUFS_PAGE_SIZE-1))

#define SUFS_MAX_CPU     224
#define SUFS_MAX_THREADS 448

#define SUFS_MAJOR 269
#define SUFS_DEV_NAME "supremefs"

#define SUFS_DEV_PATH "/dev/"SUFS_DEV_NAME

#define SUFS_PM_MAX_INS  8

#define SUFS_MOUNT_ADDR 0x400000000000

#define SUFS_ROOT_INODE 2

#define SUFS_KFS_LEASE_MAX_OWNER   1

#define SUFS_KFS_MAX_SIZE (1024ul * 1024 * 1024 * 1024)

#define SUFS_FIRST_UFS_INODE_NUM (3)

#define SUFS_MAX_INODE_NUM    16777216

#define SUFS_SUPER_PAGE_SIZE  4096

#define SUFS_MAX_PROCESS      4194304

#define SUFS_RING_ADDR 0x300000000000

#define SUFS_LEASE_RING_ADDR (SUFS_RING_ADDR)
#define SUFS_LEASE_RING_SIZE (2 * 1024 * 1024)


#define SUFS_WANTED_RING_ADDR (SUFS_LEASE_RING_ADDR + SUFS_LEASE_RING_SIZE)
#define SUFS_WANTED_RING_SIZE (SUFS_MAX_INODE_NUM / 8)

#define SUFS_MAPPED_RING_ADDR (SUFS_WANTED_RING_ADDR + SUFS_WANTED_RING_SIZE)
#define SUFS_MAPPED_RING_SIZE (SUFS_MAX_INODE_NUM / 8)

#define SUFS_DDL_RING_ADDR (SUFS_MAPPED_RING_ADDR + SUFS_MAPPED_RING_SIZE)
#define SUFS_DDL_RING_SIZE (SUFS_MAX_INODE_NUM * 8)

#define SUFS_ODIN_CNT_RING_ADDR (SUFS_DDL_RING_ADDR + SUFS_DDL_RING_SIZE)

#define SUFS_ODIN_ONE_CNT_RING_SIZE 4096

#define SUFS_ODIN_CNT_RING_TOT_SIZE (SUFS_MAX_THREADS * SUFS_ODIN_ONE_CNT_RING_SIZE)

#define SUFS_ODIN_RING_ADDR (SUFS_ODIN_CNT_RING_ADDR + SUFS_ODIN_CNT_RING_TOT_SIZE)

#define SUFS_ODIN_ONE_RING_SIZE (2 * 1024 * 1024)

#define SUFS_ODIN_RING_SIZE (SUFS_ODIN_ONE_RING_SIZE * SUFS_MAX_CPU)


#define SUFS_MIN_TGROUP         4
#define SUFS_MAX_TGROUP       256

#define SUFS_MAX_PROCESS_PER_TGROUP  32

#define SUFS_NAME_MAX         255

#define SUFS_ROOT_PERM (S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | \
                        S_IROTH | S_IWOTH)

#define SUFS_FILE_BLOCK_PAGE_CNT      8
#define SUFS_FILE_BLOCK_SIZE         (SUFS_FILE_BLOCK_PAGE_CNT * SUFS_PAGE_SIZE)
#define SUFS_FILE_BLOCK_SHIFT        15

#define SUFS_DELEGATION_ENABLE 1

#define SUFS_WRITE_DELEGATION_LIMIT 256

#define SUFS_READ_DELEGATION_LIMIT (32 * 1024)

#define SUFS_CLWB_FLUSH 1

#define SUFS_CHECKER_PASS_RET_CODE   0 


#define SUFS_CHECKER_STATE_FREE  0 
#define SUFS_CHECKER_STATE_EXIST 1

#define SUFS_MAPPED_STATE_FREE   0



#define SUFS_CPU_MHZ 2200

#define SUFS_LEASE_CYCLES (100 * SUFS_CPU_MHZ * 1000)
#define SUFS_LEASE_GRACE_CYCLES (100 * SUFS_CPU_MHZ * 1000)


#endif /* SUFS_CONFIG_H_ */
